name: vbcard-api_dev

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/pgsql/data
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './:/home/node/app'
    ports:
      - '3000:3000'
    command: 'yarn start:dev'
    depends_on:
      - db

  minio:
    image: 'minio/minio:latest'
    ports:
      - '8900:8900'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'minio:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'

volumes:
  db:
  minio:
