FROM node:22

USER node:node

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

RUN npm i -g @nestjs/cli

WORKDIR /home/node/app

COPY --chown=node:node ./docker-entrypoint.sh .

RUN chmod +x ./docker-entrypoint.sh

ENTRYPOINT [ "./docker-entrypoint.sh" ]