name: vbcard-api_test

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './:/home/node/app'
    env_file:
      - .env
    depends_on:
      - db

  minio:
    image: 'minio/minio:latest'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: 'minio server /data/minio --console-address ":8900"'
