services:
  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/pgsql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  api:
    build: .
    restart: always
    volumes:
      - './.env:/home/node/app/.env'
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  dbdata:
