services:
  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/pgsql/data
    ports:
      - 127.0.0.1:${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  api:
    build: .
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata:
