name: vbcard-api_gitlab

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.vbcard'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.vbcard'
        gitlab_rails['gitlab_shell_ssh_port'] = 24
        gitlab_rails['initial_root_password'] = "motdepasseinitial"
    ports:
      - '80:80'
      - '24:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'

  runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - 'runner_config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  runner_config:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
