name: vbcard-api_test
services:

  api:
    image: node:23
    working_dir: "/home/node/app"
    volumes:
      - "./:/home/node/app"
    ports:
      - "3000:3000"
    command: sh -c "yarn; yarn test:watch"
