name: VBCard CI/CD Workflow

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Run test inside docker compose api service
  #       run: docker compose -f docker-compose.test.yml run --rm api sh -c "yarn; yarn test src/authentication/"

  # build:
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Log in to the github container registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ github.token }}

  #     - name: Build and push to the github container registry
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
  #         push: true

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker compose remote deployment
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_ed25519
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/id_ed25519
          DOCKER_HOST=“ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} docker ps -a

      # - name: executing remote ssh commands using key
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     # port: ${{ secrets.SSH_PORT }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd www
      #       git pull origin main
      #       docker compose down
      #       docker compose up -d
