name: VBCard CI/CD Workflow

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run test inside docker compose api service
              run: docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml run --rm api sh -c "yarn; yarn test"