name: VBCard CI/CD Workflow

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use NodeJS
              uses: actions/setup-node@v4
              with:
                node_version: "23"
            - name: Install dependencies
              run: yarn
            - run: yarn test